version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - ./api/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  api:
    build: ./api
    volumes:
      - ./api:/trivia
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
  ui:
    build: ./ui
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    ports:
      - "3001:3001"
