version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - ./api/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: ./api
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/trivia
    ports:
      - "3000:3000"
    depends_on:
      - db
  ui:
    build: ./ui
    volumes: 
      - ./ui:/ui
    ports: 
      - "3001:3001"
