name: Trivia CI
on: push
jobs:
  rake:
    name: "Rails CI"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: "password"
        ports: ["5432:5432"]    
    steps:
      - uses: actions/checkout@v2
      - name: Build the Rails app
        run: docker build -t opentriviadeluxe:latest -t opentriviadeluxe:${GITHUB_SHA} api/
      - name: Sanity check 1
        run: echo `pwd`
      - name: Sanity check 2
        run: ls -la
      - name: Make tmp and log writeable
        run: chmod -R 666 api/tmp/ api/logs/
      - name: Run Rails tests and Rubocop (linter)
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
        run: docker run --rm -v `pwd`/api:/trivia opentriviadeluxe:latest -- bin/rake
  